### ISSUE TITLE
Does this package support .NET 4.6.1?

### ISSUE THREAD

**Issue by chrisstewart** [Thashiznets/PWDTK.NET#2]
We're currently using this package on .NET 4.5.2 and would like to upgrade.  I don't see anything that would suggest it doesn't, but it also doesn't explicitly specify that it does.

**Comment by realindiahotel** [comment]
Hi Chris,
The source will be fine to upgrade to 4.6.1
Cheers

On Tue, Jan 26, 2016 at 7:44 AM -0800, "Chris Stewart" notifications@github.com wrote:

We're currently using this package on .NET 4.5.2 and would like to upgrade.  I don't see anything that would suggest it doesn't, but it also doesn't explicitly specify that it does.

---

Reply to this email directly or view it on GitHub:
https://github.com/Thashiznets/PWDTK.NET/issues/2

**Comment by realindiahotel** [comment]
Chris updated the source to support newer .NET framework.
